createExpense:
  handler: src/handlers/expenses/createExpense.execute
  environment:
    RECEIPTS_BUCKET_NAME: ${self:custom.environment.RECEIPTS_BUCKET_NAME}
    REGION: ${self:custom.environment.REGION}
  events:
    - httpApi:
        method: POST
        path: /expenses
        authorizer:
          name: cognitoAuthorizer

listExpenses:
  handler: src/handlers/expenses/listExpenses.execute
  events:
    - httpApi:
        method: GET
        path: /expenses
        authorizer:
          name: cognitoAuthorizer

getExpensesSummary:
  handler: src/handlers/expenses/getExpensesSummary.execute
  events:
    - httpApi:
        method: GET
        path: /expenses/summary
        authorizer:
          name: cognitoAuthorizer

getReceiptUploadUrl:
  handler: src/handlers/expenses/getReceiptUploadUrl.execute
  environment:
    RECEIPTS_BUCKET_NAME: ${self:custom.environment.RECEIPTS_BUCKET_NAME}
    REGION: ${self:custom.environment.REGION}
  events:
    - httpApi:
        method: GET
        path: /expenses/receipt-upload-url
        authorizer:
          name: cognitoAuthorizer

editExpense:
  handler: src/handlers/expenses/editExpense.execute
  environment:
    RECEIPTS_BUCKET_NAME: ${self:custom.environment.RECEIPTS_BUCKET_NAME}
    REGION: ${self:custom.environment.REGION}
  events:
    - httpApi:
        method: PUT
        path: /expenses/{expenseId}
        authorizer:
          name: cognitoAuthorizer

removeExpense:
  handler: src/handlers/expenses/removeExpense.execute
  environment:
    RECEIPTS_BUCKET_NAME: ${self:custom.environment.RECEIPTS_BUCKET_NAME}
    REGION: ${self:custom.environment.REGION}
  events:
    - httpApi:
        method: DELETE
        path: /expenses/{expenseId}
        authorizer:
          name: cognitoAuthorizer

getReceiptViewUrl:
  handler: src/handlers/expenses/getReceiptViewUrl.execute
  environment:
    RECEIPTS_BUCKET_NAME: ${self:custom.environment.RECEIPTS_BUCKET_NAME}
    REGION: ${self:custom.environment.REGION}
  events:
    - httpApi:
        method: GET
        path: /expenses/{expenseId}/receipt
        authorizer:
          name: cognitoAuthorizer
