service: resgatar-community

frameworkVersion: "3"

custom:
  environment: ${file(./config/${self:provider.stage}.json):environment}
  esbuild: ${file(esbuild.config.js)}
  prune:
    automatic: true
    number: 0

provider:
  name: aws
  runtime: nodejs24.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'hml'}
  environment:
    STAGE: ${self:provider.stage}
    SERVICE_NAME: ${self:custom.environment.SERVICE}
    USER_POOL_ID: ${self:custom.environment.USER_POOL_ID}
    CLIENT_ID: ${self:custom.environment.CLIENT_ID}
    DB: ${self:custom.environment.DB}

  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${self:custom.environment.COGNITO_URL}
        audience:
          - ${self:custom.environment.CLIENT_ID}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminInitiateAuth
        - cognito-idp:AdminDeleteUser
        - cognito-idp:AdminSetUserPassword
        - cognito-idp:AdminUpdateUserAttributes
        - cognito-idp:AdminRespondToAuthChallenge
        - cognito-idp:AdminGetUser
        - cognito-idp:ListUsers
      Resource:
        - ${self:custom.environment.COGNITO_USER_POOL_ARN}

plugins:
  - serverless-esbuild
  - serverless-prune-plugin

functions:
  createMember:
    handler: src/handlers/members/createMember.execute
    events:
      - httpApi:
          path: /members
          method: POST
          authorizer:
            name: cognitoAuthorizer

  removeMember:
    handler: src/handlers/members/removeMember.execute
    events:
      - httpApi:
          path: /members/{memberId}
          method: DELETE
          authorizer:
            name: cognitoAuthorizer

  listMembers:
    handler: src/handlers/members/listMembers.execute
    events:
      - httpApi:
          method: GET
          path: /members/list
          authorizer:
            name: cognitoAuthorizer

  getMember:
    handler: src/handlers/members/getMember.execute
    events:
      - httpApi:
          method: GET
          path: /members
          authorizer:
            name: cognitoAuthorizer

  editMember:
    handler: src/handlers/members/editMember.execute
    events:
      - httpApi:
          method: PUT
          path: /members/{memberId}
          authorizer:
            name: cognitoAuthorizer

  updatePassword:
    handler: src/handlers/members/updatePassword.execute
    events:
      - httpApi:
          method: PUT
          path: /members/password
          authorizer:
            name: cognitoAuthorizer

  createCharge:
    handler: src/handlers/charges/createCharge.execute
    environment:
      MPAGO_ACCESS_TOKEN: ${self:custom.environment.MPAGO_ACCESS_TOKEN}
      MPAGO_TRANSACTION_URL: ${self:custom.environment.MPAGO_TRANSACTION_URL}
    events:
      - httpApi:
          method: POST
          path: /charges
          authorizer:
            name: cognitoAuthorizer

  consultCharge:
    handler: src/handlers/charges/consultCharge.execute
    environment:
      MPAGO_ACCESS_TOKEN: ${self:custom.environment.MPAGO_ACCESS_TOKEN}
      MPAGO_TRANSACTION_URL: ${self:custom.environment.MPAGO_TRANSACTION_URL}
    events:
      - httpApi:
          method: GET
          path: /charges/{transactionId}
          authorizer:
            name: cognitoAuthorizer

  createNewContributionByYear:
    handler: src/handlers/contributions/createNewContributionByYear.execute
    events:
      - httpApi:
          method: POST
          path: /contributions
          authorizer:
            name: cognitoAuthorizer

  createNotification:
    handler: src/handlers/notifications/createNotification.execute
    events:
      - httpApi:
          method: POST
          path: /notifications
          authorizer:
            name: cognitoAuthorizer

  listNotifications:
    handler: src/handlers/notifications/listNotifications.execute
    events:
      - httpApi:
          method: GET
          path: /notifications
          authorizer:
            name: cognitoAuthorizer
