createCharge:
  handler: src/handlers/charges/createCharge.execute
  environment:
    ENCRYPTION_KEY: ${self:custom.environment.ENCRYPTION_KEY}
    MPAGO_ACCESS_TOKEN: ${self:custom.environment.MPAGO_ACCESS_TOKEN}
    MPAGO_TRANSACTION_URL: ${self:custom.environment.MPAGO_TRANSACTION_URL}
    MPAGO_NOTIFICATION_URL: ${self:custom.environment.MPAGO_NOTIFICATION_URL}
  events:
    - httpApi:
        method: POST
        path: /charges
        authorizer:
          name: cognitoAuthorizer

registerCashPayment:
  handler: src/handlers/charges/registerCashPayment.execute
  environment:
    FIREBASE_SERVICE_ACCOUNT: ${self:custom.environment.FIREBASE_SERVICE_ACCOUNT}
  events:
    - httpApi:
        method: POST
        path: /charges/cash
        authorizer:
          name: cognitoAuthorizer

getChargesSummary:
  handler: src/handlers/charges/getChargesSummary.execute
  events:
    - httpApi:
        method: GET
        path: /charges/summary
        authorizer:
          name: cognitoAuthorizer

consultCharge:
  handler: src/handlers/charges/consultCharge.execute
  environment:
    ENCRYPTION_KEY: ${self:custom.environment.ENCRYPTION_KEY}
  events:
    - httpApi:
        method: GET
        path: /charges/{transactionId}
        authorizer:
          name: cognitoAuthorizer
